ALTER TABLE `tbldomains` CHANGE `urlforwarding` `dnsmanagement` TEXT NOT NULL ;
UPDATE `tblconfiguration` SET setting='DomainDNSManagement' WHERE setting='DomainURLForwarding' ;
ALTER TABLE `tbldomainpricing` ADD `dnsmanagement` TEXT NOT NULL AFTER `renew` , ADD `emailforwarding` TEXT NOT NULL AFTER `dnsmanagement` ;
INSERT INTO `tblconfiguration` (`setting` ,`value` )VALUES ('DomainIDProtection','5.00');
ALTER TABLE `tbldomainpricing` ADD `idprotection` TEXT NOT NULL AFTER `emailforwarding` ;
ALTER TABLE `tbldomainpricing` ADD `eppcode` TEXT NOT NULL AFTER `idprotection` ;
ALTER TABLE `tbldomains` ADD `idprotection` TEXT NOT NULL ;
ALTER TABLE `tblclients` CHANGE `status` `status` ENUM( "Active", "Inactive" ) NOT NULL ;
ALTER TABLE `tblhosting` CHANGE `domainstatus` `domainstatus` ENUM( "Pending", "Active", "Suspended", "Terminated" ) NOT NULL ;
ALTER TABLE `tblhostingaddons` CHANGE `status` `status` ENUM( "Pending", "Active", "Suspended", "Terminated" ) NOT NULL ;
ALTER TABLE `tbldomains` CHANGE `status` `status` ENUM( "Pending", "Active", "Expired" ) NOT NULL ;
DELETE FROM tblemailtemplates WHERE type='addon';
DELETE FROM tblemailtemplates WHERE name='Domain Subscription Payment Confirmation';
DELETE FROM tblemailtemplates WHERE name='Subscription Payment Confirmation';
DELETE FROM tblemailtemplates WHERE name='Subscription Payment Due';
INSERT INTO `tblemailtemplates` (type,name,subject,message) VALUES ('domain', 'Domain Transfer Initiated', 'Domain Transfer Initiated', '<p>Dear [CustomerName], </p><p>Thank you for your domain transfer order. Your order has been received and we have now initiated the transfer process. The details of the domain purchase are below: </p><p>Domain: [Domain]<br />Registration Length: [RegPeriod]<br />Transfer Price: [FirstPaymentAmount]<br />Renewal Price: [RecurringAmount]<br />Next Due Date: [NextDueDate] </p><p>You may login to your client area at [ClientAreaLink] to manage your domain. </p><p>[Signature] </p>');
INSERT INTO `tblemailtemplates` (type,name,subject,message) VALUES ('domain', 'Domain Renewal Confirmation', 'Domain Renewal Confirmation', '<p>Dear [CustomerName], </p><p>Thank you for your domain renewal order. Your domain renewal request for the domain listed below has now been completed.</p><p>Domain: [Domain]<br />Renewal Length: [RegPeriod]<br />Renewal Price: [RecurringAmount]<br />Next Due Date: [NextDueDate] </p><p>You may login to your client area at [ClientAreaLink] to manage your domain. </p><p>[Signature] </p>');
INSERT INTO `tblemailtemplates` (type,name,subject,message) VALUES ('domain', 'Upcoming Domain Renewal Notice', 'Upcoming Domain Renewal Notice', '<p>Dear [CustomerName], </p><p>The domain name listed below will expire in [DaysUntilExpiry] days.</p><p>[Domain] - [NextDueDate]</p><p>To ensure the domain does not expire, you should renew it now. You can do this from the domains management section of our client area here: [ClientAreaLink]</p><p>Should you allow the domain to expire, you will be able to renew it for up to 30 days after the renewal date. During this time, the domain will not be accessible so any web site or email services associated with it will stop working.</p><p>[Signature]</p>');
INSERT INTO `tblconfiguration` (`setting` ,`value` )VALUES ('DomainRenewalNotices', '30,7,-3,0,0');
UPDATE tblpaymentgateways SET value='Invoices' WHERE gateway='paypal' AND setting='type' ;
UPDATE tblpaymentgateways SET value='PayPal' WHERE gateway='paypal' AND setting='name' ;
UPDATE tblhosting SET paymentmethod='paypal' WHERE paymentmethod='paypalinvoices';
UPDATE tblhostingaddons SET paymentmethod='paypal' WHERE paymentmethod='paypalinvoices';
UPDATE tbldomains SET paymentmethod='paypal' WHERE paymentmethod='paypalinvoices';
UPDATE tblinvoices SET paymentmethod='paypal' WHERE paymentmethod='paypalinvoices';
UPDATE tblaccounts SET gateway='paypal' WHERE gateway='paypalinvoices';
UPDATE tblorders SET paymentmethod='paypal' WHERE paymentmethod='paypalinvoices';
DELETE FROM tblpaymentgateways WHERE gateway='paypal' AND setting='style' ;
DELETE FROM tblpaymentgateways WHERE gateway='paypalinvoices';
INSERT INTO `tblpaymentgateways` (`gateway`, `type`, `setting`, `name`, `description`) VALUES ('paypal', 'yesno', 'forcesubscriptions', 'Force Subscriptions', 'Tick this box to hide the one time payment button when a subscription can be created');
ALTER TABLE `tbltickets` ADD `replyingadmin` INT( 1 ) NOT NULL , ADD `replyingtime` DATETIME NOT NULL ;
INSERT INTO `tblconfiguration` (`setting` ,`value` )VALUES ('SequentialInvoiceNumbering', '');
INSERT INTO `tblconfiguration` (`setting` ,`value` )VALUES ('SequentialInvoiceNumberFormat', '{NUMBER}');
INSERT INTO `tblconfiguration` (`setting`, `value`) VALUES ('SequentialInvoiceNumberValue', '1');
DELETE FROM tblconfiguration WHERE setting='InvoiceSubscriptionPayments';
ALTER TABLE `tblservers` CHANGE `primarynameserver` `nameserver1` TEXT NOT NULL ,CHANGE `primarynameserverip` `nameserver1ip` TEXT NOT NULL ,CHANGE `secondarynameserver` `nameserver2` TEXT NOT NULL ,CHANGE `secondarynameserverip` `nameserver2ip` TEXT NOT NULL ;
ALTER TABLE `tblservers` ADD `nameserver3` TEXT NOT NULL AFTER `nameserver2ip` ,ADD `nameserver3ip` TEXT NOT NULL AFTER `nameserver3` ,ADD `nameserver4` TEXT NOT NULL AFTER `nameserver3ip` ,ADD `nameserver4ip` TEXT NOT NULL AFTER `nameserver4` ;
INSERT INTO `tblconfiguration` (`setting` ,`value` )VALUES ('DefaultNameserver3', '');
INSERT INTO `tblconfiguration` (`setting` ,`value` )VALUES ('DefaultNameserver4', '');
ALTER TABLE `tblservers` ADD `accesshash` TEXT NOT NULL AFTER `password` ;
UPDATE `tblhosting` SET nextinvoicedate = nextduedate;
UPDATE `tbldomains` SET nextinvoicedate = nextduedate;
UPDATE `tblhostingaddons` SET nextinvoicedate = nextduedate;
